//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestDemo_Crawford.Testdata {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestdataValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestdataValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestDemo_Crawford.Testdata.TestdataValidation", typeof(TestdataValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/crawfordandco.
        /// </summary>
        internal static string crawfordFacebookURL {
            get {
                return ResourceManager.GetString("crawfordFacebookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eve.
        /// </summary>
        internal static string firstName1 {
            get {
                return ResourceManager.GetString("firstName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sergio.
        /// </summary>
        internal static string firstName2 {
            get {
                return ResourceManager.GetString("firstName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home | Crawford &amp; Company | United Kingdom.
        /// </summary>
        internal static string homePageTitle {
            get {
                return ResourceManager.GetString("homePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Holt.
        /// </summary>
        internal static string lastName1 {
            get {
                return ResourceManager.GetString("lastName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramos.
        /// </summary>
        internal static string lastName2 {
            get {
                return ResourceManager.GetString("lastName2", resourceCulture);
            }
        }
    }
}
